from itertools import combinations

from sage.matrix.constructor import matrix
from sage.misc.misc_c import prod
from sage.rings.ideal import Ideal
from sage.rings.polynomial.polynomial_ring_constructor import PolynomialRing
from sage.rings.qqbar import QQbar
from sage.symbolic.ring import SR
from sage_acsv.data.exceptions import ACSVException


def is_transverse_at_point(H, vs, pt):
    r"""Determines if point ``pt`` lies at a transverse multiple point of ``V(H)``.

    INPUT:

    * ``H`` -- A polynomial
    * ``vs`` -- A list of variables
    * ``pt`` -- A point

    OUTPUT:

    ``True`` or ``False`` verifying if ``V(H)`` is transverse at ``pt``

    EXAMPLES::

        sage: from sage_acsv.helpers import is_transverse_at_point
        sage: R.<x,y> = PolynomialRing(QQ, 2)
        sage: is_transverse_at_point(y^2-x^2-x^3-x^4, [x, y], [0, 0])
        True
        sage: is_transverse_at_point(y^2-x^3-x^2-x^4, [x, y], [1, 1]) # Not a point in V(H)
        False
        sage: is_transverse_at_point((1-x)^2*(1-y)^2+(2-x-y)*(3-2*x-y), [x, y], [1, 1])
        True
        sage: is_transverse_at_point(x^2-y^3, [x, y], [0, 0])
        False
        sage: R.<x,y,z> = PolynomialRing(QQ, 3)
        sage: is_transverse_at_point((x-y+z^3)^3 * (x+y), [x, y, z], [0, 0, 0])
        True
        sage: is_transverse_at_point(x*y-z^3, [x, y, z], [0, 0, 0])
        False

    """
    R = PolynomialRing(QQbar, len(vs), vs)
    H = R(H)
    vs = [R(v) for v in vs]

    if H.subs({v: w for v, w in zip(vs, pt)}) != 0:
        return False
    
    def hom(f):
        if f == 0:
            return 0
        f = R(f)
        return f.homogeneous_components().get(min(f.homogeneous_components().keys()))

    # Step 1: Check that the leading homogeneous part of H factors nicely
    # Shift H so pt is at the origin
    H = H.subs({v: v + w for v, w in zip(vs, pt)})
    factors, multiplicities = zip(*hom(H).factor())
    if any(f.degree() > 1 for f in factors):
        return False

    # Step 2. Compute hom of singular set at pt
    Id = Ideal([H, *H.gradient()])

    # Convert to reverse graded ring in one additional variable and homogenize
    z0 = SR.var('z0')
    R_ordered, new_vars = PolynomialRing(QQbar, [z0] + vs, order='deglex').objgens()
    z0 = new_vars[0]
    Id = Id.change_ring(R_ordered)
    Id_hom = Id.homogenize(z0)
    gb = Id_hom.groebner_basis()
    tangent_cone = Ideal([hom(f.subs({z0:1})) for f in gb]).change_ring(R)

    # Step 3: Compute the ideal generated by removing one factor from the leading hom of H
    J = Ideal([
        factors[i]**(multiplicities[i]-1) * prod(factors[j]**multiplicities[j] for j in range(len(factors)) if j != i)
        for i in range(len(factors))
    ])

    return tangent_cone == J


def _compute_transverse_factorization_at_point(H, vs, pt):
    r"""Computes the factorization of ``H`` around the point ``pt`` and checks that
    it is transverse.

    INPUT:

    * ``H`` -- A polynomial
    * ``vs`` -- A list of variables appearing in ``H``
    * ``pt`` -- A dictionary mapping ``vs``to an algebraic value

    OUTPUT:

    The leading coefficient, a list of factors of ``H`` that vanish at ``pt``, a list with their multiplicities, and a list
    of all remaining factors.
    """
    factors = []
    extra_factors = []
    poly_factors = H.factor()
    unit = poly_factors.unit()
    factors = []
    multiplicities = []
    for factor, multiplicity in poly_factors:
        const = factor.coefficients()[-1]
        unit *= const**multiplicity
        factor /= const
        if factor.subs(pt) != 0:
            extra_factors.append(factor**multiplicity)
            continue
        factors.append(factor)
        multiplicities.append(multiplicity)
    s = len(factors)
    normals = matrix(
        [[f.derivative(v).subs(pt) for v in vs] for f in factors]
    )
    if normals.rank() < s:
        raise ACSVException(
            "Not a transverse intersection. Cannot deal with this case."
        )

    return unit, factors, multiplicities, extra_factors


def _find_parametrizing_order(factors, vs, r, cp):
    r"""Reorders ``vs``, ``r``, and ``cp`` so that the first s coordinates of ``vs`` parametrize
    the remaining d-s coordinates locally near ``cp``, where s is the number of ``factors``.

    INPUT:

    * ``factors`` -- A list of polynomials
    * ``vs`` -- A list of variables
    * ``r`` -- A list of algebraic values
    * ``cp`` -- A list of algebraic values

    OUTPUT:

    A list of factors of ``H`` that vanish at ``pt``, a list with their multiplicities, and a list
    of all remaining factors.
    """
    s = len(factors)
    d = len(vs)
    pt = {vs[i]: cp[i] for i in range(d)}
    last_block = tuple(range(d-s, d))
    subsets = [last_block] + [
        c for c in combinations(range(d), s) if c != last_block
    ]
    for Rset in subsets:
        Jac = matrix(
            [
                [(vs[j] * Q.derivative(vs[j])).subs(pt) for j in Rset]
                for Q in factors
            ]
        )
        if Jac.determinant() != 0:
            if Rset != last_block:
                perm = [j for j in range(d) if j not in Rset] + list(Rset)
                vs = list(vs[j] for j in perm)
                r = list(r[j] for j in perm)
                cp = list(cp[j] for j in perm)
            break
    else:
        raise ACSVException("Cannot find parametrizing set.")

    return vs, r, cp
